twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    globals:
        photos_directory: 'uploads/photos/'

when@test:
    twig:
        strict_variables: true
