version: '3'

services:
###> doctrine/doctrine-bundle ###

  mysql_test:
    image: mysql
    ports:
      - "3308:3306"
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: symfony_mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_test
      MYSQL_USER: symfony_test
      MYSQL_PASSWORD: symfony_test

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  your-service:
    build: .
    command: sh -c 'chmod -R 777 /app/public/uploads/photos'
    volumes:
      - ./public/uploads/photos:/app/public/uploads/photos

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
